create_weather_query = """
    CREATE TABLE IF NOT EXISTS weather ( weather_date TIMESTAMP,
    cloudBaseAvg DOUBLE, cloudBaseMax DOUBLE, cloudBaseMin DOUBLE, cloudCeilingAvg DOUBLE,
    cloudCeilingMax DOUBLE, cloudCeilingMin DOUBLE, cloudCoverAvg INTEGER, cloudCoverMax INTEGER,
    cloudCoverMin INTEGER, dewPointAvg DOUBLE, dewPointMax DOUBLE, dewPointMin DOUBLE,
    evapotranspirationAvg DOUBLE, evapotranspirationMax DOUBLE, evapotranspirationMin DOUBLE,
    evapotranspirationSum DOUBLE, freezingRainIntensityAvg INTEGER, freezingRainIntensityMax INTEGER,
    freezingRainIntensityMin INTEGER, hailProbabilityAvg DOUBLE, hailProbabilityMax DOUBLE,
    hailProbabilityMin DOUBLE, hailSizeAvg DOUBLE, hailSizeMax DOUBLE, hailSizeMin DOUBLE,
    humidityAvg INTEGER, humidityMax INTEGER, humidityMin INTEGER, iceAccumulationAvg INTEGER,
    iceAccumulationLweAvg INTEGER, iceAccumulationLweMax INTEGER, iceAccumulationLweMin INTEGER,
    iceAccumulationLweSum INTEGER, iceAccumulationMax INTEGER, iceAccumulationMin INTEGER,
    iceAccumulationSum INTEGER, moonriseTime VARCHAR, moonsetTime VARCHAR,
    precipitationProbabilityAvg INTEGER, precipitationProbabilityMax INTEGER,
    precipitationProbabilityMin INTEGER, pressureSeaLevelAvg INTEGER, pressureSeaLevelMax INTEGER,
    pressureSeaLevelMin INTEGER, pressureSurfaceLevelAvg INTEGER, pressureSurfaceLevelMax INTEGER,
    pressureSurfaceLevelMin INTEGER, rainAccumulationAvg INTEGER, rainAccumulationLweAvg INTEGER,
    rainAccumulationLweMax INTEGER, rainAccumulationLweMin INTEGER, rainAccumulationMax INTEGER,
    rainAccumulationMin INTEGER, rainAccumulationSum INTEGER, rainIntensityAvg INTEGER,
    rainIntensityMax INTEGER, rainIntensityMin INTEGER, sleetAccumulationAvg INTEGER,
    sleetAccumulationLweAvg INTEGER, sleetAccumulationLweMax INTEGER, sleetAccumulationLweMin INTEGER,
    sleetAccumulationLweSum INTEGER, sleetAccumulationMax INTEGER, sleetAccumulationMin INTEGER,
    sleetIntensityAvg INTEGER, sleetIntensityMax INTEGER, sleetIntensityMin INTEGER,
    snowAccumulationAvg INTEGER, snowAccumulationLweAvg INTEGER, snowAccumulationLweMax INTEGER,
    snowAccumulationLweMin INTEGER, snowAccumulationLweSum INTEGER, snowAccumulationMax INTEGER,
    snowAccumulationMin INTEGER, snowAccumulationSum INTEGER, snowDepthAvg INTEGER, snowDepthMax INTEGER,
    snowDepthMin INTEGER, snowDepthSum INTEGER, snowIntensityAvg INTEGER, snowIntensityMax INTEGER,
    snowIntensityMin INTEGER, sunriseTime VARCHAR, sunsetTime VARCHAR, temperatureApparentAvg DOUBLE,
    temperatureApparentMax DOUBLE, temperatureApparentMin DOUBLE, temperatureAvg DOUBLE,
    temperatureMax DOUBLE, temperatureMin DOUBLE, uvHealthConcernAvg INTEGER, uvHealthConcernMax INTEGER,
    uvHealthConcernMin INTEGER, uvIndexAvg INTEGER, uvIndexMax INTEGER, uvIndexMin INTEGER,
    visibilityAvg DOUBLE, visibilityMax DOUBLE, visibilityMin DOUBLE, weatherCodeMax INTEGER,
    weatherCodeMin INTEGER, windDirectionAvg INTEGER, windGustAvg DOUBLE, windGustMax DOUBLE,
    windGustMin DOUBLE, windSpeedAvg DOUBLE, windSpeedMax DOUBLE, windSpeedMin INTEGER
)
"""